#=========== dein.vim ==========
# vimプラグイン管理

[[plugins]]
repo = 'Shougo/dein.vim'

#========== vim-airline ==========
#画面下部にステータスバーを表示

[[plugins]]
repo    = 'vim-airline/vim-airline'
depends = ['vim-airline-themes']
hook_add = '''
  let g:airline_powerline_fonts = 1

  " INSERTモードとNORMALモードの切替遅延を無くす
  " https://github.com/bling/vim-airline/wiki/FAQ#there-is-a-pause-when-leaving-insert-mode
  " https://yukidarake.hateblo.jp/entry/2015/07/10/201356
  " set timeout timeoutlen=50
  " <ESC><ESC>で:nohlsearchと競合するため、200に設定
  " <ESC>長押しで:nohlsearch発火
  set timeout timeoutlen=200
'''

[[plugins]]
repo = 'vim-airline/vim-airline-themes'
hook_add = '''
  let g:airline_theme = 'bubblegum'
'''

#========== nerdtree ==========
#ファイラー

[[plugins]]
repo = 'scrooloose/nerdtree'
hook_add = '''
  nnoremap <silent><C-n> :NERDTreeToggle<CR>
  " ブックマークを初期表示
  let g:NERDTreeShowBookmarks=1
  " autocmd vimenter * NERDTree
  " Vim起動時にNERDTreeを表示
'''
