name: macos

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  macos-test:
    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v2

    # Error Check
    - name: copy
      run : |
        cp -r ${GITHUB_WORKSPACE} ~/
        cd ~/dotfiles
        make run
