name: macos

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  macos-test:
    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v2

    # Error Check
    - name: copy
      run : |
        cp -r ${GITHUB_WORKSPACE} ~/
    - name: remove ACL
      run : |
        chmod -N "/Volumes/Macintosh HD/Users/runner"
        chmod -N "/Volumes/Macintosh HD/Users/runner/.config"
    - name: unlink node@12
      run : |
        brew unlink node@12
    - name: run
      run : |
        cd ~/dotfiles
        make run

    - name: Load .zprofile
      run : |
        zsh ~/.zprofile 2> /tmp/dotfiles/.zprofile.error.log
        cat /tmp/dotfiles/.zprofile.error.log
        if [ -s /tmp/dotfiles/.zprofile.error.log ]; then false; fi

    - name: Load .zshrc
      run : |
        zsh ~/.zshrc 2> /tmp/dotfiles/.zshrc.error.log
        cat /tmp/dotfiles/.zshrc.error.log
        if [ -s /tmp/dotfiles/.zshrc.error.log ]; then false; fi
