name: master branch

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Install required packages
      run : |
        sudo apt-get install shellcheck
        sudo apt-get install zsh

    - name: Check bin/*.sh
      run : shellcheck ${GITHUB_WORKSPACE}/bin/*.sh

    - name: Check .zprofile
      run : zsh -n ${GITHUB_WORKSPACE}/.zprofile

    - name: Check .zshrc
      run : zsh -n ${GITHUB_WORKSPACE}/.zshrc

  macos-setup:
    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v2

    - name: Copy
      run : |
        cp -r ${GITHUB_WORKSPACE} ~/

    # Default installed node conflicts with homebrew's one
    - name: Unlink node@12
      run : |
        brew unlink node@12

    - name: Run
      run : |
        cd ~/dotfiles
        export BREW_BUNDLE_CORE_ONLY=1
        make run

    # Use error.log. Not be able to use 'set -e' in .zprofile
    - name: Load .zprofile
      run : |
        touch error.log
        zsh ~/.zprofile 2> error.log
        cat error.log
        if [ -s error.log ]; then false; fi

    # Use error.log. Not be able to use 'set -e' in .zshrc
    - name: Load .zshrc
      run : |
        touch error.log
        zsh ~/.zshrc 2> error.log
        cat error.log
        if [ -s error.log ]; then false; fi

