name: Ubuntu Setup (all packages)"

on:
  push:
    paths:
    - 'bin/packages-init-ubuntu/**'
    branches: [ master ]
  pull_request:
    paths:
    - 'bin/packages-init-ubuntu/**'
    branches: [ master ]

jobs:
  ubuntu-setup:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Copy
      run : |
        cp -r ${GITHUB_WORKSPACE} ~/

    - name: Run
      run : >
        cd ~/dotfiles &&
        sudo bash -c '
        export SKIP_ZSH_INIT=1 &&
        make'

    # Use error.log. Not be able to use 'set -e' in .zprofile
    - name: Load .zprofile
      run : |
        touch error.log
        zsh ~/.zprofile 2> error.log
        cat error.log
        if [ -s error.log ]; then false; fi

    # Use error.log. Not be able to use 'set -e' in .zshrc
    - name: Load .zshrc
      run : |
        touch error.log
        zsh ~/.zshrc 2> error.log
        cat error.log
        if [ -s error.log ]; then false; fi

